inherit_from: .rubocop_todo.yml
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
    - spec/**/*
    - lib/tasks/auto_annotate_models.rake

Metrics/MethodLength:
  Exclude:
  - db/**/*
  
Metrics/LineLength:
  Exclude:
  - db/**/*

Style/StringLiterals:
  Exclude:
    - db/schema.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - db/schema.rb

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - db/schema.rb